version: '3.8'
services:

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    restart: always
    volumes:
      - "./postgre/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"


  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - db

  api:
    build: .
    container_name: currencyapi
    restart: always
    environment:
      - REDIS_URL=cache:6379
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_Name=postgres
    ports:
      - "8081:8081"

    depends_on:
      - redis
networks:
  default:
    external:
      name: currencynetwork



